name: Playwright Tests HW 31
on: push

jobs:
  playwright-staging:
    name: 'Playwright Tests HW 31 - Staging'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests on Staging
        run: npx playwright test
        env:
          ENVIRONMENT: staging
      - name: Save Staging report
        uses: actions/upload-artifact@v4
        with:
          path: playwright-report/
          name: Staging report
        if: always()

  playwright-prod:
    name: 'Playwright Tests HW 31 - Production'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests on Production
        run: npx playwright test
        env:
          ENVIRONMENT: prod
      - name: Save Production report
        uses: actions/upload-artifact@v4
        with:
          path: playwright-report/
          name: Production report
        if: always()